'use client'

import ArticleLayout from '@/app/components/ArticleLayout'

export default function Article() {
  return (
    <ArticleLayout
      title="The Land of Opportunities?"
      date="Aug 18, 2024"
      author="Siya Patel"
      readTime="5 min read"
      tags={["Self Improvement", "Self Improvement Tips", "Self Improvement Goals", "Life", "Life Lessons"]}
    >
      <h2>An ode to self-improvement</h2>

      <p>Thousands of immigrants moved to America for opportunity. America, the land of opportunity they say. But that is a misnomer. That implies that opportunity grows on trees, but the fruit of a tree is meant to be grasped by all, no matter the size or status of the hand. Rather, opportunity is mass produced in low quality in factories and shipped out with high price tags to bougie retail stores. They are laid out all clean and pristine, almost mocking us, saying, &quot;come look at me, I don&apos;t bite.&quot; Propped up proudly on a pedestal behind a pane of glass, we are left window shopping. But window shopping only gets our hopes up, not our dreams. Opportunity has become a shell of a word because we sold its soul to capitalism. It no longer adorns the blindfold sacred to Queen Justice. Rather, it throws up its hands, too afraid to take responsibility. The scales...They have tipped, and they aren&apos;t in our favor. We must balance them again, against all odds. We will balance them again-with the weight of our existence.</p>

      <p>This is a ode to doing just that. Balancing the scales again with the weight of our own existence. But what does that really mean? How do we balance the scales?</p>

      <p>Here are the first steps to how we can balance the scales again. Trust me, they work.</p>

      <ol>
        <li>Tell yourself you are not a victim. We often find comfort in being the victim, in being sad, and in being at a low. This is because it provides us an extrinsic fault for, an excuse, and a reason to not work hard. It&apos;s easy throwing up your hands by telling yourself you are the victim of your own circumstances. The great equalizer is choice. We all are given a choice, you must make the choice to de-victimize yourself. Happiness is a choice. To have the strength to balance the scales, we have to mentally prepare ourselves. That preparation is a choice. Even with your circumstances, you choose how you feel. So choose positive. Choose growth. Once you realize you are not a victim and have free-will, you are 50% there.</li>
        <li>Just because you don&apos;t see it, doesn&apos;t mean it isn&apos;t there. We tend to live in a bubble because it provides us comfort. Seeing the world for how big and competitive it is is scary. When we refuse to see the outside world, we block out any room for growth and opportunities. So no, what you are doing currently isn&apos;t enough. (Maybe it is, who am I to judge?). As someone from a minority, a first-generation college student, and from a lower socio-economic status, we never realize what&apos;s going on around us. Step 2 is about staying informed. Stay on top of things, and recognize everything you don&apos;t know. You may not know about quantum mechanics, but that means you should embrace it, don&apos;t cower the other way. You may not know about how to apply to college, embrace that. Learn from it. Master it. You may not know about this new internship opportunity, so take time and go out of your way to find these things on your own. You may not know how to get a job at NASA, how to get an insider deal, or how to get an early research opportunity. You have to constantly explore to find out what you don&apos;t know, and then work even harder to KNOW. When the scales are tipped against us, people will not come give us things, we have to go find it. Knowledge is always in demand, so make yourself marketable. To grow yourself, you have to identify what you don&apos;t know. The only way you identify what you don&apos;t know is by exploring. EXPLORE EVERYTHING. LEARN EVERYTHING.</li>
        <li>Learn to be uncomfortable. You are just as important as those around you. I&apos;ve noticed a common pattern amongst people from disadvantaged backgrounds, including myself; we are scared or intimidated by authority and confrontation. When I say authority, simply people with a higher status (or we assume they have a higher status because status is simply a sociological phenomenon that we all adhere to). Why are we scared of talking to the CEO? Why are we scared of asking an expert a question? Now this is a generalization, please-this doesn&apos;t apply to everyone all the time. The only reason Oppenheimer got the opportunity to make the atomic bomb was because he straight up went and asked the project manager (this doesn&apos;t mean you should make an atomic bomb). Learn to do that to. Don&apos;t be afraid to ask experts and professionals questions. Don&apos;t be afraid to talk to that boss about potential salary changes. Don&apos;t be afraid to ask for what you want and why things should go your way. You deserve to voice your wants and opinions. Opportunities and growth won&apos;t land in our laps, we have to go get them. Sometimes, that is as simple as having an uncomfortable conversation with someone. Its always uncomfortable at first until its not. Learning to be uncomfortable means developing a sense of confidence and respect. You are human, you are hardworking, and you deserve change. Those three factors alone give you more than enough reason to pursue personal growth and demand change.</li>
      </ol>

      <p>Wow, that was a lot of words. See, not too bad, right? I live by these three rules. Anything that gets in the way of these three rules maybe isn&apos;t great for you. Not Maybe, FOR SURE-they are not great for you. Okay, so I gave you a list. What about it though? These three steps helped me set myself up for success. I grew up in a household that knew nothing about college. As low-income immigrants, we didn&apos;t understand how to win in the world around us. These three steps are what I took to take initiative of my own life. If you are tired of simply floating along, losing, or not making a conscious impact, these three steps will take you out of that toxic loophole. These aren&apos;t steps to bring you high status and money in life. They could be, but that&apos;s not their point. The point is to make you a strong and confident person. To give you a voice in your own life and in society. By doing so, you are then well equipped to push the scale of inequality back towards equality. No longer will status or background be a disadvantage, but rather a strength.</p>

      <p>These steps helped me feel as though my existence had weight, and maybe they can do the same for you.</p>
    </ArticleLayout>
  )
} 